name: Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "10"
      - run: wget -O - https://github.com/gohugoio/hugo/releases/download/v0.60.1/hugo_0.60.1_Linux-64bit.tar.gz| tar xz
      - run: ./hugo
      - run: npm install -g firebase-tools
      - run: firebase deploy
        working-directory: public
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
